# Generated by Django 4.0.4 on 2022-05-30 04:52
import django.db.models.deletion
import mubo.apps.shortcodes.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(help_text="The URL to be shortened")),
                (
                    "code",
                    models.CharField(
                        default=mubo.apps.shortcodes.models.generate_short_code,
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "hits",
                    models.PositiveBigIntegerField(
                        default=0,
                        editable=False,
                        help_text="Number of times this short code has been hit",
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
